version: '3.8'

services:
  # Application: Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DATABASE=base
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AES_SECRET_KEY=R3zmKTgCnAp1m0zRd5DCVmTA3GQhYPYd+iJsbk1+l9c=
    depends_on:
      - db
      - redis

  # Database: PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: spring-boot-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: base
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache & Lock: Redis
  redis:
    image: redis:7-alpine
    container_name: spring-boot-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # Monitoring: Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: spring-boot-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

volumes:
  postgres_data:
